# Generated by Django 3.2 on 2025-06-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hastane', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Yatak Numarası')),
                ('room', models.CharField(max_length=50, verbose_name='Oda')),
                ('status', models.CharField(choices=[('boş', 'Boş'), ('dolu', 'Dolu')], default='boş', max_length=20, verbose_name='Durum')),
            ],
        ),
    ]
