# Generated by Django 3.2 on 2025-06-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hastane', '0002_beds'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='entry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
