# Generated by Django 3.2 on 2025-06-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hastane', '0002_beds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Oda Numarası')),
                ('status', models.CharField(choices=[('boş', 'Boş'), ('dolu', 'Dolu')], default='boş', max_length=20, verbose_name='Durum')),
                ('room_type', models.CharField(choices=[('tek', 'Tek Kişilik'), ('cift', 'Çift Kişilik')], default='tek', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Beds',
        ),
    ]
