# Generated by Django 3.2 on 2025-06-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hastane', '0003_auto_20250623_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Oda Numarası'),
        ),
    ]
