# Generated by Django 3.2 on 2025-06-25 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hastane', '0003_auto_20250623_1922'),
        ('hastane', '0004_alter_rooms_number'),
    ]

    operations = [
    ]
