# Generated by Django 3.2 on 2025-06-25 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hastane', '0005_merge_0003_auto_20250623_1922_0004_alter_rooms_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='speciality',
        ),
    ]
