# Generated by Django 3.2 on 2025-07-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hastane', '0006_remove_doctors_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
